# Practice Problems

In this practice problem, we will practice
* pseudocode
* appropriate scope
* validating inputs
* modular programming


# Problem 001      
## “1001 Coins”
 
There are 1001 5c coins lined up on a table.

I come along and replace every second coin with a 10c coin.

Then I replace every third coin with a 20c coin.

Finally, I replace every fourth coin with a 50c coin.

How much money is on the table?
 


## The problem as Pseudocode

1. Make an array of length N
2. Fill each element with 5. 
```
    For each element at index `i`
    - Set value to 5
```
3. Fill every second element with 10.
```
    FOR each element at index `i`
        IF `i` is divisible by 2 THEN
            `array[i]` <- 10
        ENDIF
    ENDFOR
```    

4. Fill every third element with 20.
```
    FOR each element at index `i` 
        IF `i` is divisible by 3 THEN
            `array[i]` <- 20
        ENDIF
    ENDFOR
```        
5. Fill every fourth element with 50.
```
    FOR each element at index `i` 
        IF `i` is divisible by 4 THEN
            `array[i]` <- 50
        ENDIF
    ENDFOR
```
6. Sum all elements
```
    sum <- 0
    FOR each element at index `i` 
        sum <- sum + array[i]
    ENDFOR
```


In [1]:
import numpy as np

In [2]:
N = 10
NUMBER_OF_COINS = 10

In [13]:
# 1. Make an array of length N
coins = np.zeros(N)
coins

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
coins.dtype

dtype('float64')

In [15]:
# 2. Fill each element with 5
v = 5
coin_value = 5
for i in range(N):
    coins[i] = coin_value
coins

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# 3. Fill every second value with 10
coin_value = 10
for i in range(N):
    # Check if the index is divisible by 2

In [20]:
def is_divisible(value, divisor):
    """Return True if `value` is divisible by `divisor`"""
    return value % divisor == 0

In [28]:
assert is_divisible(9, 3)
assert not is_divisible(10, 3)
# assert not is_divisible(10, -1)

In [36]:
# Alternate array solution
N = 5
arr = np.ones(N) * 5
arr[1::2] = 10
arr[2::3] = 20
arr[3::4] = 50
arr.sum()

90.0

In [37]:
arr

array([ 5., 10., 20., 50.,  5.])